apiVersion: v1
kind: Secret
metadata:
  name: kite-kubeconfig
  namespace: default
type: Opaque
stringData:
  kubeconfig: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpakNDQVRDZ0F3SUJBZ0lSQUtkK3MwMjdYOENsMnBaQnVtT3VFUHN3Q2dZSUtvWkl6ajBFQXdJd0ZURVQKTUJFR0ExVUVDaE1LYTNWaVpYSnVaWFJsY3pBZUZ3MHlOVEV5TWpReU1ETXpNalphRncwek5URXlNakl5TURNegpNalphTUJVeEV6QVJCZ05WQkFvVENtdDFZbVZ5Ym1WMFpYTXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CCkJ3TkNBQVE1Yzd5K2l0blJBRERJUDFmYUJmdjNMVTF5bHJNcFd6RGlHZXZQcmNKQ3c4dVo5UUFJR3daSTdrWnUKb2dQcWZXdUlBUmdTaVIwQzJKa2pvSzJJS3ZkSW8yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FvUXdIUVlEVlIwbApCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPCkJCWUVGRnQ1cnkzMERYUDVONVdhWUtIaWNaMG1LaFpmTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSVFEbjRvU04KVHJ0NTZVZUtEd2QwMVk2SnRnaWcxaXBoUnQ3MU0wWEJySmJidFFJZ1R3ai8yclZsNzBKR2dZbXlrQkRrbmlaaAp5ZVJjSG1RYVBjUXR5cER1V2JjPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        server: https://192.168.2.2:6443
      name: kubernetes
    contexts:
    - context:
        cluster: kubernetes
        namespace: default
        user: admin@kubernetes
      name: admin@kubernetes
    current-context: admin@kubernetes
    kind: Config
    users:
    - name: admin@kubernetes
      user:
        client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJoVENDQVN1Z0F3SUJBZ0lSQUtlSmRJYWJrcko2NzNXTWNMc0xSRE13Q2dZSUtvWkl6ajBFQXdJd0ZURVQKTUJFR0ExVUVDaE1LYTNWaVpYSnVaWFJsY3pBZUZ3MHlOVEV5TWpReU1ETXpNamxhRncweU5qRXlNalF5TURNegpNemxhTUNreEZ6QVZCZ05WQkFvVERuTjVjM1JsYlRwdFlYTjBaWEp6TVE0d0RBWURWUVFERXdWaFpHMXBiakJaCk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQk5oT3Roa3FZWmppdm1rLzFxNHBXNjBSRk9RcW4zY1kKVDF1cytoZnA5djEzanhSY1Z5Q1RVMWI5MlFlalUrYXFHcm5tNGhLTTdwbWN2VnpUUnVuVGx5ZWpTREJHTUE0RwpBMVVkRHdFQi93UUVBd0lGb0RBVEJnTlZIU1VFRERBS0JnZ3JCZ0VGQlFjREFqQWZCZ05WSFNNRUdEQVdnQlJiCmVhOHQ5QTF6K1RlVm1tQ2g0bkdkSmlvV1h6QUtCZ2dxaGtqT1BRUURBZ05JQURCRkFpRUF3QUVNV0hnWlJMbG8KTzdTUngyeWwxK2N1UGU0YzlDYy9PdURRWDU0WGhvb0NJRFM3TjRzdUVjekZnbHgvZUtySXI0RFJlWUp1c2lVWgpYcCtwakxLa082MUUKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
        client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUtIRTU0K29pS0E4RHBDak1rOUt5QzhGZE5HbTJlUEZjNHc4U05RMjdiWmJvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFMkU2MkdTcGhtT0srYVQvV3JpbGJyUkVVNUNxZmR4aFBXNno2RituMi9YZVBGRnhYSUpOVApWdjNaQjZOVDVxb2F1ZWJpRW96dW1aeTlYTk5HNmRPWEp3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
