apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:99jyvnnGB3wauKxNro+noHxMivD8wq+r0QTwsxK3ljKZvD6Ju3bbaQ==,iv:R6sgY6X6gEJVjr4ZmfeREDsM7jHUCxa2tft6k0Hoxnk=,tag:trsT8WuwnzX3ubrg98s3cw==,type:str]
sops:
  age:
    - recipient: age1u4hprdnt30055c0wmllcrs0z4ala4p54jhaw5zk2r8ep0daw7alszlrqye
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoQ2RYQ0E3MUdCOW5EbnZF
        TVhUS2hNald3QTNNbFFyUU1kaWZtNUg3MjBvCjM4bG5ZSEhOenA0cVJ3a3JkbEtR
        OUdhalhDR1p4ZHg0WlJWV05ucDFHWkEKLS0tIFpMSEtjYytpVTZxRStWZ0RLRU9R
        SUtjT24zdld0dXZFUEZzQWF3amVzZlUKqODWnWk7nBiu65XellS8SgoTfAJKAtvq
        bQ8tYCJ/oqUNtolt+oIKcdDl9x3U9uMZxtMHGcpJKBNSrraeVzHw+g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-23T21:42:43Z"
  mac: ENC[AES256_GCM,data:meKVCynjdPa4HLUf1tRO5dngouXhKtM+2xpWERGD+4XOObhSOxMNJofdBSzRHtPPnTIcmDxCiCCEbabwXSYLde0PFL9SfU9qdjn9+WpG1iZ3MiOtphTWl+/rYRY9vc7qFVaICRrOSN1mUO/kKn0TxkNUKZmiOSn8Nrd/Z+KXSyA=,iv:mOBhBKjkWZQM+Q5eURQWNl1RDvqV76bFJ7ytRuXHv+o=,tag:V1o9II3dEkeZl1/a6nwJAg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
