apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:Bj5ywQDXgvWJuej1rg9sJR10j1+nTMGu46FoYoxgnK8d39Oy5Ps2Vw==,iv:OJCMA+MdKUr0wQvkK8Qqln/xkll/5lJPfQ9IYOXh/D0=,tag:icVK8CWk6UDU0mQwy19q+Q==,type:str]
sops:
  age:
    - recipient: age1u4hprdnt30055c0wmllcrs0z4ala4p54jhaw5zk2r8ep0daw7alszlrqye
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrblo3KysvQk5VMHI5MDVV
        YmJWVFJlQUtMaEtwbU1ka1kxU1lObUhqL1RjClBWRy9Cb2tBa3laZGJIa0RuYUZR
        L0Vpc2RzSXJkR1JXWEJ5d3dndFU1U0UKLS0tIGRrOHlEZUxjc3duR2Vndks0aVpJ
        Um9zdlBGaHdSMlVTZmprT3VJa2NiMVkK+AzUQH1rUIvsKlMYfyZk4+isZuk1zdVj
        Ve4Qmes+eim3iC78ZAhmKMHbXWBestxPfn6cB0EN9R+GNT1SD0j31g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-24T15:30:01Z"
  mac: ENC[AES256_GCM,data:S/Z/+CtnyUUNNlctBuoKse+CGjYWeiAgvL3Kvz0A8xSzJsynIUmIqHJDawH4SerFFZTMO4k9M30j/M3caRiYvjhaqXSHrFMWn4oDipyNXfRCwJ6s2pNe9UMDW0rmjiMdEcB89r9u+uxpKluRngy5QsAyTr+nMpruEj66Pngh5+I=,iv:kC/a02eWxeAxv0kNcVgPSE6VIjR0WSfjdvl2UKjm/vE=,tag:bzHWF2OORijXuztH9eR3iQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
