apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:v9etkUY2+Si8jTuimiA4nIeWEDtmQSoydB2HtvpcwDeF1saiBBF1sg==,iv:J1XqAakbXzco95ONZh85IxLvhFCLr9FaI9fVLSpXLyY=,tag:/VYuZYGwDd/hAmoVpUFoWw==,type:str]
sops:
  age:
    - recipient: age1u4hprdnt30055c0wmllcrs0z4ala4p54jhaw5zk2r8ep0daw7alszlrqye
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaeU5yQXJPN0xidlM5eHhm
        SG9yMytPdWdwVFF6QUg2L0hUNXp4MGY4bEY4CncvdW1kUUNZdnZYVEpENWdydThF
        clBNekJVVHZ0WlVPMjRad3ZNMGUvSHMKLS0tIFNCQjdiVGszTVkrdFVkdk9YWUF3
        Rkg5R0pEREVHaW44cmNkbElSSm9aZmcKdwl3Z3e92KIMvt0H9ZVXM7AcyUY5XvWD
        6FW37/eN9Je+7bbicFAhVzAhDTVERBJcAINAnPkj2gHUDV7ARuqC/w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-24T16:08:59Z"
  mac: ENC[AES256_GCM,data:hoLWJ0O6KFZJrv66ZChnwzk6LXXQtvLayU/QkYSbC6bG2E1lnwqVV7XTIwYv8+eWaZa07MuWrbscbvA4eWhjesONePdlnXRtTedQdTsKSW6B6ZWj+F0Oqj4heofTKwjjcj6+sKH6kFJn0ZWX4UthEn6ED32NAEPGxJVbwvo8hFo=,iv:pojCOhAYyuj2Ci3IoxsNuf1JWTfASxutQ4gJw2wTcH4=,tag:jgsdXLSOg+j1JMUemOSS3A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
