apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:1kaC8JUHIn3YS7lXRQJtqSFnasc8WQEVWgEkRJ8l6jv26Z0NbquKMQ==,iv:ObxIf6QP4nhuGjfc46OsJ/mIb5um0LB83H36LRndALU=,tag:O47TyxLlE4AwwTyphvBhsg==,type:str]
sops:
  age:
    - recipient: age1u4hprdnt30055c0wmllcrs0z4ala4p54jhaw5zk2r8ep0daw7alszlrqye
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvQ0JWNzZ5ZTd6N0pEVFFr
        bHFjODMxa1ZwenBwU3NqMmNmN1pYaVcxMFJ3Ck1Xd1kvQTlZb1pwSUlKUEF0bGQ2
        THp1OWdRci9sMnovakl4c09TRHhnSWsKLS0tIDNpVG1OaGRwelhadnVFMlNiWFkr
        N0YvMDNtL09uSS9WSWVUdy85bEl4SXMKurtfkdu7EXbWV5VEwfNZSnhvUB9nLPvO
        RVCggDLE6fwNPjiZi0sDkINHBMY+PTi6m7ZNUkTTw43f3p7CV4gTXw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-24T17:27:15Z"
  mac: ENC[AES256_GCM,data:aVwxFtSYBkeffCm7RlDIv5s73fTIMDhtvTwQjcKsi2uqYsAhnZ/cQHe6p2qaXu0fD1aFLR0SEUxJUV2eXXD6uFHBWuHm5n8Fh/foa3xJO0Bqy0acSnSYZjiQ5ebnfCdaQYIQDEHByshnAPfBlxZSwg+l0tpcO8oBE35gvKkIROI=,iv:3ES1wHGWAypkbeeR0fhlQoNOr4eIFQ2A7VD2PJzk9gk=,tag:MLwjqviN23I2UEu67gTXDA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
