apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:NYgv9mvz5YBWR1lKwA==,iv:C3rg2brRqoGdrkk8Qy1JyksSZ9RghmIRyARGpxYprlE=,tag:T89tzx6cLhVx6gaV7RLhrw==,type:str]
    SECRET_PG_USERNAME: ENC[AES256_GCM,data:1Mr3FyBgaEQ=,iv:PecjKhZshN2dQ2ksr6IYeGJQKCW8M+RXSHf7Xded8CU=,tag:vwLnZkE0nxjCZ+nY7WXPTA==,type:str]
    SECRET_PG_PASSWORD: ENC[AES256_GCM,data:VKywNJE3qloR,iv:5Eh7AUU3wVLAq6JLSVLoGa5uHNKrJYWuBhbsPtkDamY=,tag:mQR/N57jQxj40ovyDZLBpQ==,type:str]
sops:
    age:
        - recipient: age1u4hprdnt30055c0wmllcrs0z4ala4p54jhaw5zk2r8ep0daw7alszlrqye
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0N012c0grT2tIdlEwa2x1
            RWFXQnlSM2pjUzVWZ210Zm5Ncnl3MmFFWFVjClFONWJrUkF1TkNsblc5MUlQK05p
            ei9oSEgxdUZWTWQveW9jVmMxNGRLRmcKLS0tIEg3cGNMVzVJMUJHZ0Z3V29BWUdx
            R3VRNDEvSFNoUEEzUVJtOTZQMTRHeVUKLcdYGCFmZhV9HH3ddc9RyI8zixGII3W2
            SxkS4YTEb+YF/xtg/5KMWUkUQcpHbC4IuK2J27/LGslNx/dGIYh1SA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-24T22:08:41Z"
    mac: ENC[AES256_GCM,data:l40yciJCJKx09KXpX6pwnCUhQYtiPM/glqRQzBS1OTghdEeKhPyTo85g82ld2xSzc23rYHwQ6pJah7pgQkGFkVF6s1yGQelbm1dmKGss8emlOPSdAuoXTFN1TVQnjwJZsvTRtqUZM5+YWzTTiOC9tfOYYkUbS4v4jRB9UNdFKfY=,iv:vC32Fo02ggfQlzUyvQGUTf60fb+Wh9DE2j/FFTt3bEo=,tag:s+bY59RlfVWMpHvAd+gl1g==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
