apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:NYgv9mvz5YBWR1lKwA==,iv:C3rg2brRqoGdrkk8Qy1JyksSZ9RghmIRyARGpxYprlE=,tag:T89tzx6cLhVx6gaV7RLhrw==,type:str]
sops:
  age:
    - recipient: age1u4hprdnt30055c0wmllcrs0z4ala4p54jhaw5zk2r8ep0daw7alszlrqye
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0N012c0grT2tIdlEwa2x1
        RWFXQnlSM2pjUzVWZ210Zm5Ncnl3MmFFWFVjClFONWJrUkF1TkNsblc5MUlQK05p
        ei9oSEgxdUZWTWQveW9jVmMxNGRLRmcKLS0tIEg3cGNMVzVJMUJHZ0Z3V29BWUdx
        R3VRNDEvSFNoUEEzUVJtOTZQMTRHeVUKLcdYGCFmZhV9HH3ddc9RyI8zixGII3W2
        SxkS4YTEb+YF/xtg/5KMWUkUQcpHbC4IuK2J27/LGslNx/dGIYh1SA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-24T17:27:15Z"
  mac: ENC[AES256_GCM,data:hg9l5KrDbyKS1laURDVSsdA8RxnD4md/IRXZfncCFr53erno9oGsoh1y8VGutYa42fsFLLjB/DKQxsxGQrtCyeBeqoeWDfngXQrx0jXeJhbyoOZ8w4IGyrh0Qk4WI4V8R6pmEpWKq+Ck5uSNsUTP+rRdFZJNghpaJ96vm3vSjtA=,iv:BjqG0bdpmgmXZthYAEwiuLs+5lqnfk1oeY2gIBqkMH0=,tag:6SMMk+OgiK/XEYYQa/ua5A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
