apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:4nZ8u0nKrGqeuB09WQ==,iv:SczPJ+rX5KZ5+eqQ/jZZAeXiQQ+4QAz6+/xly30LW4Q=,tag:Hy+Q2TgQY4KsF3jIffHp+Q==,type:str]
sops:
  age:
    - recipient: age1u4hprdnt30055c0wmllcrs0z4ala4p54jhaw5zk2r8ep0daw7alszlrqye
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBid0p4dnRDZFMzZmFiN2lL
        aTVvU1EyeitseHpmaDBpTVBlMGpkMkRiVDE0CjdjeFNic3N1WTJFT3QxaXFSblNJ
        QjJZMGE2SWt4N1hRenc3QmlzQmE4RzQKLS0tIGs3SDhVaW94R2x6WWg1UFRWanhD
        dW9McmxSMGJmZy9OcE1QaDFqRTIrKzgK70+s3iL5ztBAkMxMJ1FSjoBdyRz/WIZT
        eJ4yVSPrkL/C+O6GBCUfMlCWPcbM15pPJJUyo+I8WGeYs6+/Gv1v3g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-24T16:08:58Z"
  mac: ENC[AES256_GCM,data:X3ImkpvK9iBMkh5KJNSx+Qwn0gg59tXevyUoiE0Ri8NRIykd+4m0q4Trinrt+6Bw9omcqDRJWO1ePN+KCGKI+9gM3soAev7s5PYVaVsbbOAaVuY2lJrsfuOjlMdEbbGZZf2RHMfwJjwkRkS/fZbxtj+eYY4w6WenmZ1sLbIsJno=,iv:lkO7v0wk50i5A7P4IvrAF4N2woBcNkNfRqCMtXU5qIQ=,tag:E2CHD61TqoslgBKB136fhw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
