apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:LoTPKGtvh8tdDH+uBw==,iv:fRrovPNtUoI8qkBOa7bQZIjkIWTjKcgZaE6AzclpQ90=,tag:aWR0lmjCHg0G/LpeXj8rxA==,type:str]
sops:
  age:
    - recipient: age1u4hprdnt30055c0wmllcrs0z4ala4p54jhaw5zk2r8ep0daw7alszlrqye
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSER0N05yRU0zRnR5TXgw
        cFREREE5Zk5jQkJNb3AyczJTRVY3WldiWEdJCkhlblZTb3gxRFBkU1NsVUFxVDlP
        N3QvSE5BTVcrRzVlNEFMcGl3MHhsY0UKLS0tIDZhU1ZPYWJ6UlQ5c3FPdlJqT1Bu
        UDkwZUhQakxRM2V1YWdEelJpZW9MTUUKtSPrO539is93243QexQlC934N5PomsHo
        3HWGHPyINYMjJRfktKGN9/MG7sMeo5PYy+kDNSrKgmAoS5MSMBZKjQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-23T21:42:42Z"
  mac: ENC[AES256_GCM,data:1LSaPCnIJbnLWgBtLhifEOlnKelc7mfdEHluSy5lr8Io/l26WOUCiIFS/rrmcgBbvNmD5VcS3CAUh7gcf6ryKWZ9P6xeAOfigaKMn3qIv94imMGz8f4OWlgyto+cd/lYSvJxK6X+McVuuo6o63JkaEMTAcoCErLHceXS+cItudU=,iv:4QQRYIl8PzJS7ElplN6uNXg1LIfartdMcFpcSD4mjXw=,tag:pYFW/xtyVfHDhVAnuwbTog==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
