apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:NYgv9mvz5YBWR1lKwA==,iv:C3rg2brRqoGdrkk8Qy1JyksSZ9RghmIRyARGpxYprlE=,tag:T89tzx6cLhVx6gaV7RLhrw==,type:str]
    SECRET_DOMAIN_TWO: ENC[AES256_GCM,data:xGIhnZmbG/RYC7s=,iv:K77EZO9xWdvNMi4rstLgzkhJT7oh/Cj8oz5h7fiXN70=,tag:fbw34x9VSDJP4xnbU364dQ==,type:str]
    SECRET_DOMAIN_THREE: ENC[AES256_GCM,data:n4Jb5ccW9uqz5585IFeq,iv:vyhwOwzwHrV9lmWxd7eyTZKBHQnzr0DZZVFhJiCZRS4=,tag:ONLwWHdWE3rfFHvtalYMLA==,type:str]
    SECRET_PG_USERNAME: ENC[AES256_GCM,data:1Mr3FyBgaEQ=,iv:PecjKhZshN2dQ2ksr6IYeGJQKCW8M+RXSHf7Xded8CU=,tag:vwLnZkE0nxjCZ+nY7WXPTA==,type:str]
    SECRET_PG_PASSWORD: ENC[AES256_GCM,data:VKywNJE3qloR,iv:5Eh7AUU3wVLAq6JLSVLoGa5uHNKrJYWuBhbsPtkDamY=,tag:mQR/N57jQxj40ovyDZLBpQ==,type:str]
    SECRET_ADGUARD_USERNAME: ENC[AES256_GCM,data:XShjQuYf+A==,iv:Z2PnwSdQV27KlUcxI4ZPZkz/x+tEBhJVF3q0gLgfWzQ=,tag:MJ+BLjFNONTIKP8XcOFcMw==,type:str]
sops:
    age:
        - recipient: age1u4hprdnt30055c0wmllcrs0z4ala4p54jhaw5zk2r8ep0daw7alszlrqye
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0N012c0grT2tIdlEwa2x1
            RWFXQnlSM2pjUzVWZ210Zm5Ncnl3MmFFWFVjClFONWJrUkF1TkNsblc5MUlQK05p
            ei9oSEgxdUZWTWQveW9jVmMxNGRLRmcKLS0tIEg3cGNMVzVJMUJHZ0Z3V29BWUdx
            R3VRNDEvSFNoUEEzUVJtOTZQMTRHeVUKLcdYGCFmZhV9HH3ddc9RyI8zixGII3W2
            SxkS4YTEb+YF/xtg/5KMWUkUQcpHbC4IuK2J27/LGslNx/dGIYh1SA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-10T21:12:04Z"
    mac: ENC[AES256_GCM,data:0Rfbhpe38gYg5Lv5y0k2enmBwS64fn4oAWDwRB6OJlMkVzRCOU+6hGBMILgtNd4+C1hpcHG0vjC69QbRBHvV7Y48/t0rkdXA3obbzM1+Xk58qJ4t+EXvhre7oVlFNsbx6SpA2oYS5tIA4M6yGgr1bqpXs3/8GZjWRZobZId0oPE=,iv:dsa/Zkb897h2Y1wcJw1mHUP6UaQs+5hnEBuU+qab7LM=,tag:ZrHjGX/p9Y+q3WQNARxsrQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
