apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:qnScJz070JxoigfYFQ==,iv:/1b7UcoanrYS/HZNcTInv5Mhp3LaM73AxxR1Ux+JW4A=,tag:sCxZ8jiwDJv75YyDYoh4gg==,type:str]
sops:
  age:
    - recipient: age1u4hprdnt30055c0wmllcrs0z4ala4p54jhaw5zk2r8ep0daw7alszlrqye
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBENkxHbExNMURzZ3pTUC9Y
        VGJBUU9sM093c015UW9MZmJHR1pMdEsxd0RZCjlwSG5YTm9GdkpvVEcxOGR6WXlV
        Q25FWUtuNHZYNXJxRXIyTmg4Rzl3NFEKLS0tIHJYQnBNNS9BSjVxTHJLMm5aVHl4
        MU8xOTRYWndaSGR0RWs5UmNGYjd6U1UKk/+0szJwhIzronIAIYeN1MSSXpI592rY
        ub1xfxYNYGaBEWXckbcuIKvd4SFi/wU0BVWBBvuN7t2QFWrcgn9cbA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-24T15:30:01Z"
  mac: ENC[AES256_GCM,data:+xPIfTfKnRp3lfOunpUR5xJ+voL1DNpE/a9gp2vlZooiLi5BaId/fhVfN2yhWze9fRAeB7aDFORRP06eWCzAoeHYkE3WaaL6pXTIwleqAeilyLcQCbmPOpv8JsPYsPNfTvI8iN/yxxE9KCU81wMQg/Scj61yPh2sPpFYVX80wDI=,iv:HYEfKo70UlYx3uJcCqtrIOoQBq0dh1GiJhxlKS1ZDhQ=,tag:/w/CaIEEqIq65EWp/2j6Ng==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
