apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:S0xzG/uthOv2vjPM5vbd7L/gPFLCT2dzh3DpuCwj6GY=,iv:KxP5doAd+AZbFdVi/Tz4qW1EXYULlBu/Un/dOAxAJuA=,tag:mWFrIfGLlT2tR3NKA+7p8A==,type:str]
sops:
  age:
    - recipient: age1u4hprdnt30055c0wmllcrs0z4ala4p54jhaw5zk2r8ep0daw7alszlrqye
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvQ3hTQmhVeWs3cDRSZ25r
        WlJVY3RzV0t3c2xocmR0REcvVG5OTDJnSDNNClluSVFFN01qQlpQWG5FckllcE5r
        Mk5wa3R2eVQ5cVV5WUpwWUx3WC9HTGcKLS0tIGVSZ2ZrK1F6TjFrWHJxbFNkZnVw
        aW91YnJwTTZTZk9vU1lDUzAvVjB4WTAKVI1gr0jOU3wFUD7uypejASyiUlI9g6aS
        gxQnzJbT4vSZo0fpjMELx/yAbcJ4ZVyJzv/eDBnlatTnQVyng6smNw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-23T21:42:42Z"
  mac: ENC[AES256_GCM,data:eeYOuRPx+GnlyjpvETxXZuplwDu6nKPis42r9cv9Gg6F9iz6keSc4z/TdEXDGrf0Sr7YT0W4UIWgOzZrWqA7KfZzlU27498kUUUHfk7ZxjBFkpNLqQeC3BdFEcSEDRn5qE8cbBY8Hk6DntvYzmEzHdcv05tspCEhmzF7X7aNN8I=,iv:8nksD53EcLzsVkvF4Pguq6DUTlo8FFs/9TR6eYTv92I=,tag:FrwO4C9PxclVK4cpj29OmQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
