apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:MuD5+RkbuVkorAQeAQd2py34ObEx66gDnqgvJd9ujfc=,iv:JJVjmIBzR8PWpFc5p//FpClRLvYh5yH2hjtwKcozeRI=,tag:68SX6+dMZX9Pvncc3QyRug==,type:str]
sops:
  age:
    - recipient: age1u4hprdnt30055c0wmllcrs0z4ala4p54jhaw5zk2r8ep0daw7alszlrqye
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBb1Y2WFo4VEFUZzZKbUpx
        QWtCN21XYVkwTmpVTzF4OUVnbTlGK1B3UGljCm1GbXpNeTNZbHhrUFFuZUtXdC9y
        OFNtVjIyaHdIUEFzcHRHRnFCT1hML2sKLS0tIGVFUVBjbWU1MUxKcThuNXZwOVZK
        MWdMNmR3SjhqR1E2SHI3RzJZb0l4akEKbiYBnYqU0sldxwbFw8xKxeF7EjppiVCg
        q8wJU4jkwWYmRTPq1ow2PknZXMFeHIbEMgPp7ufdgTDC9IoYKiQvOg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-24T15:30:01Z"
  mac: ENC[AES256_GCM,data:bpErAFtJGxW85+DBRdzx58EnjsPDDmWHu6tgLMa1L55Nhk6CYf5yAi/D5u7S7xXny+b2sp1gzOsbl37Naiv18aRL9IECE+hhWa0CRU1NpqVS8ZkOZhf7eym1Mj/Q5+lb2Sv0arI5NCDmBb+f1stE2QXJyW1U6RAgIYj2j6sLv8c=,iv:er2T2G4fL5ZO34EIcgPhoPwv4DPJmBfd2DRyhfNtSCc=,tag:ShYzXP2bmR6R/hWDN1ZiBw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
