apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:16Dib6fxFtAt57XsC3Vbwq5muA3vDWvbdRT3bOKo2Kw=,iv:jHF+kST7xaEqu2toKWks6OgyoeAG9on9ztxrCJ0XwZY=,tag:Pd1PQKDWvqFl2immnt3e2A==,type:str]
sops:
  age:
    - recipient: age1u4hprdnt30055c0wmllcrs0z4ala4p54jhaw5zk2r8ep0daw7alszlrqye
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLR2FWNFBkVkN0UWcxcTQ2
        WEI2ajZWdERnblg4L0RZejB6UEMzUEpwUlR3CnFoUzRCZUlCTVU0MXZNaDNSSHpK
        QkR5R2E3YzdHb2dLNUhFWHpIM2JLZlEKLS0tIENiSE1iR3N6V2IxN1RjRHlCS3Z5
        eUU0aGlFWk0rYkJEQWhMSWlQWWF6blUKjXhoH6h6bP3wJ89ppcXwlguoDDegkAip
        WykCJ1MYuks5eMwsakPaKcJJMhL60pyc8WZtdIEAvbu3iDhUnvXb4g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-24T17:27:15Z"
  mac: ENC[AES256_GCM,data:mcfDR0t9CeqpUbeAgvPhWgPrvdW4/M/CVz1AmuBkShZW49rQ24b2rh6LzN+ZOuwUT8/w7LmhiIJnn1HAbJKcqxml9NEPgrOfQeBukzT7IVSgNfDy/b1psU2YEwJHpgf031f6cD6xTWh1FXryvA/U8hY5z2J8TqXASP0nEexc8v4=,iv:LyX0Dx0ojZS92ZPa2x/E7v2KxBIYSMVgAJOETMdR4sg=,tag:9q1iGrSLHCyJJgcRmGZjcw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
