apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:JFgW4yxWiBZWJXWPFv15N7ylM5Z6FQy5S8mrBDkik5QqZigfLOuOsorCZ/vE3UsTUO1Mrz5a8jjKuVR5816ZKwGPFVtpT4YuPVLbePRJXbacUfETV/bcMqY7cnvpW3OrPuxeLhsFwCapIBznu18n2vcDv5th3KkD4H8wZqX1tVDLYYSdMdomVmNZZ9VALQCH1u6ef05WtgZyvHSFv1JCJvJCfta/mZ6TnSqZd0OZINpdsp35,iv:fHQw6+88vO7LJeXA0t72a2EXQbwfSMHzoMfIVXtq3tg=,tag:Tpwa6oZusRWzNk1qG3pPCA==,type:str]
sops:
  age:
    - recipient: age1u4hprdnt30055c0wmllcrs0z4ala4p54jhaw5zk2r8ep0daw7alszlrqye
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoMmFPNVBVMFZZUUJ0OFMv
        Z0R6cVVLNE9hMjVlcHl6NlNtak9JY3NaM1RFCkVBdTMzd0NQODlldVJXTm53NXBs
        ZU9NTGNtZXcwTGw4RVRGV3oxQzB4MmcKLS0tIHZVK0lCRmJpck5GbFNubXMyaUg5
        WmpLNVdzMG5iR1lvY0dSS3lJSHkremcKidpcm6EvTp5F5OwpbSzFwR5qLSiFk3yI
        9LnDd2/UYwEpvxs5DFumU243a+x7Bgyw/eQtT4eQHUnMT9tU1t+U7A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-24T16:08:59Z"
  mac: ENC[AES256_GCM,data:FpakCy9Pw4m1NBACwmKDNSVYgQPSoHmoviumBM5jWYBemefvis85t2BFtu/41WBkz7KDlrIRKJLWlWa1RfXICn5/nxu/Syj5SjXYySY5rbcj0NO9UuyuJ+hukxN6hTnrP5rKcgeQ5KsqsFDTIUnQAirZzmJLgDZ2e9U79gQ+qo0=,iv:sTL36zoNrlp0d/0GWmfY0jAXh9Mu1BQXO4z2x65VABg=,tag:JKUgfksH8xJMjHkBd5ztlA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
