apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:kbChPUR67NDb6316PzUGLjViND6j/N5iGB0tY9bUTpxaTvJDYgW4D5mjN6R+4ukykHljvcrkA379l8HzVCF6n57Etxcp0VTfoRkqfSlzAE1oV9jbRsZ0lXZDox9pSCyUKN0mfwQXIuHwnuE5iZewsxXltIMun/5zhdpz7XIu3VAHD9cf0JxhwXMRvt8lTRUOQoJQRrSEkQc4JrY8u7g9V5/EmNKJDZj1lUdZ66SyeZ0jEyUE,iv:BnZtfundd5dFxNV0LCcmP24Rjn6gM5rszttmtwsxbNI=,tag:+oZbEpLKGcC8SI+rmr1ytw==,type:str]
sops:
  age:
    - recipient: age1u4hprdnt30055c0wmllcrs0z4ala4p54jhaw5zk2r8ep0daw7alszlrqye
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSa3FTZXhETnFRYS9tem5q
        eUd0Ync1MGRQQ29ibG5JRmNnMmF4VW1KT3l3Ckh1OVZkbk9saUhnVkk5V3c2L0Mz
        RENrY2FBaEFXNkNUYzdLdXVsanJhamsKLS0tIGdqUzg3c0JhQ3FDOTMxUyt6N2pn
        NHFEUUcvYkNlbDRQY3d4eWY2ZUp4OGcKIPpbRkK3e2uwZaENJBD5Nf9HWGeFFFi1
        YZD4RqGXMEha0lhbk09EKjLIKyEkau8oVfCWF/cL4QCVk4b+fCWzFA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-24T17:27:15Z"
  mac: ENC[AES256_GCM,data:bGiP3QNtdWQinOoE0Y6ldpFsdvdZOLaGbz/O+ZJEgfjMLcGhDkdmNdSrBJXvhsA+OO+AWFrQnXRpXBbh93z4HVCzT82IaU4G/fjkE3MkQu+Py126gQ+7xU96wP6g3HHBuMl2lU8X9pgiOD73wpVxpVrzHPGkUmeQqm9UJh1N6+w=,iv:ENaj5vebliymkMU/rhTS6si8r96WJjEYPpVmwN7f6v0=,tag:Ey5hxjlAMv+tIwY3D/ylFQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
