apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:gSST2DaZSzDnO1+0sjo66e4Fe55FroA/d8KzOeehH4Yurhg0w3rVtZBq29jB48PVduULZwWlhPFN/m7MIYoQlqQsYG+Eua5ktni3YcacF4cqfPzDIfD3ir3THJD14cI5TEqmRj50Q7hT9cPHc+ID/sziIbag07n/Iqi7swOqEo37y1JCjPEJoLwftTITHFfidSjGeDh0EVdPYyuxb8JtlLnnRJLq78BoyPlvNDxay1dmCd96,iv:x6f2VroAogu0+bj9B/zKQcn8iBxvl0rA24Nc8qS3Bx0=,tag:+VFq602g5KSlc/lPdC5BXw==,type:str]
sops:
  age:
    - recipient: age1u4hprdnt30055c0wmllcrs0z4ala4p54jhaw5zk2r8ep0daw7alszlrqye
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVNmkwVjVaNGhrQ1ViQjBK
        OGk3ZTBCcStRdnc4Z3ZkMGVSRWRVcjB4Yld3CjhmN2hKaXpqNndkUGd2aUtsa09T
        TDA1UE1JUnJXT1lzOWUrb3U2MzY2TWsKLS0tIFBTOWo4c24wVnZXaVdMaVpwY2ZK
        NTJXWndqWDJ5Z29IRmxIallncEI0dDAKtCBJetvGCmct2JEluHztNGpeyci6ayEe
        gcj0sSU7dGAyNPy1+JrR8jQhGuPvM1qnLOHLqdt6c+mHC9gdoEWllQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-24T15:30:01Z"
  mac: ENC[AES256_GCM,data:BxJyrgp0g/hCUCSj9ZiG9Rp7xNC6xMaw/D6LLqf76SPO8/1LhEEXrnkYAy29NT7Sk0xLMLKaWT8LK/aBvXGVY5bF0WdtYwEa/EtxvwR0YSsuGEus8mfwLivEoTY1Iz/p87wHdFuS3FRTlq+g7V6dw27skGNs1FaWLBMcIAHLwT0=,iv:SVsMKFM37EfxIWNgeyXKj3sBuh3flIHXLL8yH3Yxjas=,tag:11DAjtQ+cHujqVcMH249dQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
