apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:CtE7/W6wlD3jHnS2yIjwQEQdyujSVGkj3Icgrp6MHAbccN9+gpg0hg==,iv:BkamGdTjILISqUO7UTQ9wpFPTzqdtRBvRqLqYcBKlI4=,tag:tPWTLsUl5ViKYSVfn8iqnQ==,type:str]
sops:
  age:
    - recipient: age1u4hprdnt30055c0wmllcrs0z4ala4p54jhaw5zk2r8ep0daw7alszlrqye
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVdUtaU0N5UmltVjlNMFVr
        aTU5U0NvQ3Q0ZzkwYTdOMGQ5TGg3bTdTY0JjClN5V29hTkFORThrY0JUMysveUhz
        TFJMSVBYT3hnWk55SGw4RENtanpGMWMKLS0tIHhiOG00Mk9yM3YwV0NOMEhpKzRD
        WVpUQmI3V0ptekcza1hremJjajQyVmMKUY7c0EAPmHR9V4n0TVEakmDLOtj903tK
        sWwqffBkqNcGKBqbUwL0of7UegkVEi3DOYal4kz/Cve1O8SUIwaTaQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-23T21:42:42Z"
  mac: ENC[AES256_GCM,data:yxWNCjX4cyTGda28d8COken7unuCoDh7r8uY35WxHVPbk3H9k3smJapl9jI65N9rjoOiIiwn4IwmDziZa4xe7cljXzpAcXqUix2GDYIqQuum+EulB9lYYu4zQl08YqxtN+1tASDqPFcMr/Z/dWO2NH2OiWg9TkKjwN24wkHtnIk=,iv:SJNYW4PsCWMN0sG7QAs++HrprXPbeSGfJm/ytFcGCbQ=,tag:OUcrhB3oY/HPhoA23UzNpQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
