apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:cWD3JNP8VEah6CvTcsNz5FoVnQ3ZOZG1W0T8ZvGRvOdkv+iv3/k9LQ==,iv:GQmqak90hQLF/ZvO2WuQwjVhA02TSPGSNTVASdqYaKI=,tag:TEzw2PoiIsdmMNXcqDkrCg==,type:str]
sops:
  age:
    - recipient: age1u4hprdnt30055c0wmllcrs0z4ala4p54jhaw5zk2r8ep0daw7alszlrqye
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Mi83UEhmaGhBKzJzd0tt
        S1Q5bFhYMlBWbGprdTZDZjFmbUFmK1RkcXhjCmZKWVlZbWZnRzVRNnRPZ2k2cEpF
        cVdla09Gc08vZW5BeTdwMGFBNDROYWcKLS0tIFlUZ1RsUHdlNzRSM1BoUEtYY0tO
        ZnlDOW1wVExVNGNmKzRhbzIyQXRqQ0EKTVc0VOMmao/3biAdqC3ALcn9uyyo2DZx
        ILCEbsJYaQq7ZEPquKsBhccKbOC3VC2TwKyjgHCWCutpYuf3tMto9Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-24T16:08:58Z"
  mac: ENC[AES256_GCM,data:ideW4JgC+Pt/BSjZh+WBc+e79NXgVexUBir2St1NTpftJ7I9mz9cdCfvejQgcivykyXlg49brGAOx8/g+BdvhOYgE9Ia96MfDVrFSQONbC/LU5mT00Efbc9Har+wyWAqm0MiynKmzDYgqPbjcGWgUD0u6kPXdDhIVjGr4t+oFdE=,iv:AYy5lPRhrdcr9+5cJtRJWN7QgBtsV29tE+k52OVpbzU=,tag:vyQc3MxUZidFjgL7csvOCQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
