apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:kq8prnjjkgtwk07iJ3dvIXOwafR+zYfEDQlPstpLIWI9Y/P385+kEg==,iv:Qz7JdohtOxCJDH0t69rhn1EymjglwdGEo+th7XUwG2U=,tag:pthlQPm9mIyXFz3QW4BJLQ==,type:str]
sops:
  age:
    - recipient: age1u4hprdnt30055c0wmllcrs0z4ala4p54jhaw5zk2r8ep0daw7alszlrqye
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnWXJZOHBXRVlsZFJ6RkFS
        eXJ5RTF5VGZDY0l2dk9iNWluOFpCbk1rcDFJClM4WE5qaHlWdExsdXNLWDQ1TFVs
        dnJYalBXRTlBY1pGS25waXhXUGhmcVEKLS0tIEs0UmxYTjFGalZFMFUxVmVZSTRC
        UVQxVXJpY1J0dWxGZWdaQktneUh1bFUK78n8isMFrJ5lX7uoSFyyOfLD3PkWn/If
        5E4PTXSggC+XMpqboW3mV4TIASeOAqaMRmfqrKKpC/QvqzF5eo45lg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-24T17:27:15Z"
  mac: ENC[AES256_GCM,data:Qqln/EckaobKzzG11E6MYB6GF1G52gdvfq6QxirAyimQNw7IKKP2p0eNO1mo5s53sPzLRF7Siw9+y/+MZqnV1Lir6gDwmPiXZZIQtHFFnF0wNcuFewdaBAWmqTzj4PlVzFpbTiHNZkFGsqvpMiRBQFtIWoaNsmNdlzhVjfaKylQ=,iv:0XfF3eh9DAU4dkBTIB+d8sgEEKBSxngIAt1bijKhFDc=,tag:fykruYsmH3DC22fZ/NhBwA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
