apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:D4Lwpf+6xQcnp/W+eXgLt8CjCTvyVBqFVl28zXkZIBio6c9T3LScSw==,iv:Wh9yeOh9meJA8IdrgaYgO9lPBPELFnEKO9xnj8FH7us=,tag:cMBveDVsTeeSvRaKxd5t2w==,type:str]
sops:
  age:
    - recipient: age1u4hprdnt30055c0wmllcrs0z4ala4p54jhaw5zk2r8ep0daw7alszlrqye
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEUnAwUGh4a1BiMmpvbFFQ
        djVYT2h2M0F1d09TY2JLTVByVlY5UzBia1RBCm00YkRPa0s5bjhZY0wveCtXd2JN
        Vk83STRqOFZOTmNZTGdkcUxuWk91WXMKLS0tIDhUKzlWY0VkMmxHdEkzaWJseXM4
        VGRRMnJJZEUrNlNVbWlneTFXdVU1TDQKs9exuI01XscZYuTApV3mKDauU0r0rToz
        qHro3nezXS5q2aZaDJEhNWKKXYSj5LuusmkqfCElx1bRow+yf1tXpA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-24T15:30:01Z"
  mac: ENC[AES256_GCM,data:Df50wJxMcz/mwkcKfZF12+ULwVkdYgVjK7q9J+YwJAdOOy/p3/tnKd47w+tAtpQjroyYgY1s0OlM1JxMlNB9h8cqnypIpLiCb2zqEfX/MpORX+Y+3AMecpuOsG1lao97hMbESVTidVe7bJR51eNlCg6FUAkKsZ1LGKIEvo1EGy4=,iv:Z2FULEhJs6X9JXya70LeK76h9NW1o4DM5xgdlBmG2+Y=,tag:A7LclLD3r4nkCOZ5OeyKdw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
