---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.2.2:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.2.2"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "io"
    ipAddress: "192.168.2.10"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/ee21ef4a5ef808a9b7484cc0dda0f25075021691c8c09a276591eedb638ea1f9
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "d8:3a:dd:44:73:e8"
        dhcp: false
        addresses:
          - "192.168.2.10/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.2.1"
        mtu: 1500
        vip:
          ip: "192.168.2.2"
  - hostname: "ganymede"
    ipAddress: "192.168.2.11"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/ee21ef4a5ef808a9b7484cc0dda0f25075021691c8c09a276591eedb638ea1f9
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "dc:a6:32:c1:35:e9"
        dhcp: false
        addresses:
          - "192.168.2.11/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.2.1"
        mtu: 1500
  - hostname: "europa"
    ipAddress: "192.168.2.12"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/ee21ef4a5ef808a9b7484cc0dda0f25075021691c8c09a276591eedb638ea1f9
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "dc:a6:32:c1:36:0d"
        dhcp: false
        addresses:
          - "192.168.2.12/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.2.1"
        mtu: 1500
  - hostname: "callisto"
    ipAddress: "192.168.2.13"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/ee21ef4a5ef808a9b7484cc0dda0f25075021691c8c09a276591eedb638ea1f9
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "dc:a6:32:c1:e2:b1"
        dhcp: false
        addresses:
          - "192.168.2.13/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.2.1"
        mtu: 1500

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/cluster.yaml"

